#!/bin/bash
env GOOS=linux GOARCH=amd64 go build
ssh cwc@cwc0.nodestone.io "sudo systemctl stop cwc-reflector"
scp cwc-reflector cwc@cwc0.nodestone.io:cwc-reflector
ssh cwc@cwc0.nodestone.io "sudo systemctl start cwc-reflector"
